# Generated by Django 4.1.3 on 2022-11-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fabrics", "0001_initial"),
        ("reviews", "0002_alter_review_fabric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="fabric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="fabrics.fabric",
            ),
        ),
    ]
