# Generated by Django 4.1.3 on 2022-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_fabric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="payload",
            field=models.CharField(max_length=1000),
        ),
    ]
