# Generated by Django 4.1.3 on 2022-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="payload",
            field=models.TextField(),
        ),
    ]
