# Generated by Django 4.1.3 on 2022-11-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qnas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qna",
            name="replied",
            field=models.BooleanField(default=False),
        ),
    ]
