# Generated by Django 4.1.3 on 2022-11-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qnas", "0002_qna_replied"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qna",
            name="replied",
        ),
    ]
